#!/bin/bash

ACCOUNTS_DIR=${ACCOUNTS_DIR:-accounts}
STUDENTS_DIR=students
TERRAFORM_DIR=${TERRAFORM_DIR:-terraform-aws-cf-install}

account_folder=$1
student_account_folder=$STUDENTS_DIR/$account_folder
if [[ "${account_folder}X" = "X" || ! -d $student_account_folder ]]; then
  echo "USAGE: cf-login account-folder"
  exit 1
fi

if [[ ! -f $student_account_folder/$TERRAFORM_DIR/terraform.tfstate ]]; then
  echo "File $student_account_folder/$TERRAFORM_DIR/terraform.tfstate is missing; and is required"
  exit 1
fi

pushd $student_account_folder/$TERRAFORM_DIR
  cf login --skip-ssl-validation \
      -a $(terraform output cf_api) \
      -u admin -p $(terraform output cf_admin_pass)
popd
