#!/bin/bash

ACCOUNTS_DIR=${ACCOUNTS_DIR:-accounts}
STUDENTS_DIR=students
TERRAFORM_DIR=${TERRAFORM_DIR:-terraform-aws-cf-install}

account_folder=$1
student_account_folder=$STUDENTS_DIR/$account_folder
if [[ "${account_folder}X" = "X" || ! -d $student_account_folder ]]; then
  echo "USAGE: terraform-aws-cf-install account-folder"
  exit 1
fi

if [[ ! -f $student_account_folder/fog-api.yml ]]; then
  echo "File $student_account_folder/fog-api.yml is missing; and is required"
  exit 1
fi

pushd $student_account_folder
rm -rf terraform-aws-cf-install
git clone https://github.com/cloudfoundry-community/terraform-aws-cf-install &&
  cd terraform-aws-cf-install &&
  fog_to_terraform -C ../fog-api.yml &&
  make plan &&
  make apply
popd
